{% set version = "1.9.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mosaic
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mosaic_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mosaic/mosaic_{{ version }}.tar.gz
  sha256: 94d3e200ea84aeffa15eae4a2be977aef1f59df9cfeae071ef25ff58de1ff050

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr
    - r-tibble
    - r-lattice >=0.20_21
    - r-ggformula
    - r-mosaicData
    - r-matrix
    - r-mosaicCore >=0.7.0
    - r-ggplot2
    - r-rlang >=0.4.7
    - r-purrr
    - r-mass
    - r-tidyr
  run:
    - r-base
    - r-base
    - r-dplyr
    - r-tibble
    - r-lattice >=0.20_21
    - r-ggformula
    - r-mosaicData
    - r-matrix
    - r-mosaicCore >=0.7.0
    - r-ggplot2
    - r-rlang >=0.4.7
    - r-purrr
    - r-mass
    - r-tidyr

test:
  commands:
    - $R -e "library('mosaic')"           # [not win]
    - "\"%R%\" -e \"library('mosaic')\""  # [win]

about:
  home: https://github.com/ProjectMOSAIC/mosaic, https://www.mosaic-web.org/mosaic/
  license: GPL-2.0-or-later
  summary: Data sets and utilities from Project MOSAIC (<http://www.mosaic-web.org>) used to teach mathematics, statistics, computation and modeling.  Funded by the NSF, Project MOSAIC is a community of educators working to tie together aspects of quantitative work that students in science, technology, engineering and mathematics
    will need in their professional lives, but which are usually taught in isolation, if at all.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - mfansler

# Package: mosaic
# Type: Package
# Title: Project MOSAIC Statistics and Mathematics Teaching Utilities
# Version: 1.9.1
# Description: Data sets and utilities from Project MOSAIC (<http://www.mosaic-web.org>) used to teach mathematics, statistics, computation and modeling.  Funded by the NSF, Project MOSAIC is a community of educators working to tie together aspects of quantitative work that students in science, technology, engineering and mathematics will need in their professional lives, but which are usually taught in isolation, if at all.
# Authors@R: c( person(given = "Randall",  family = "Pruim", email = "rpruim@calvin.edu", role = c("aut", "cre")), person(given = "Daniel T.",   family = "Kaplan", email = "dtkaplan@macalester.edu", role = "aut"), person(given = "Nicholas J.", family = "Horton", email = "nhorton@amherst.edu", role = "aut") )
# Depends: R (>= 4.1),
# Imports: dplyr, tibble, lattice (>= 0.20-21), ggformula, mosaicData, Matrix, mosaicCore (>= 0.7.0), ggplot2, rlang (>= 0.4.7), purrr, MASS, grid, tidyr, methods, utils
# Suggests: ggstance, ggridges, vdiffr, lubridate, magrittr, NHANES, RCurl, sp, vcd, testthat (>= 3.0.0), knitr, tools, parallel, mapproj, rgl, rmarkdown, covr, formatR, palmerpenguins, ggrepel, readr, ggdendro, gridExtra, splines, latticeExtra, glue, broom, leaflet
# Enhances: manipulate
# VignetteBuilder: knitr
# License: GPL (>= 2)
# LazyLoad: yes
# LazyData: yes
# URL: https://github.com/ProjectMOSAIC/mosaic, https://www.mosaic-web.org/mosaic/
# BugReports: https://github.com/ProjectMOSAIC/mosaic/issues
# RoxygenNote: 7.3.1
# Roxygen: list(markdown = TRUE)
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2025-01-13 05:37:13 UTC; root
# Author: Randall Pruim [aut, cre], Daniel T. Kaplan [aut], Nicholas J. Horton [aut]
# Maintainer: Randall Pruim <rpruim@calvin.edu>
# Repository: CRAN
# Date/Publication: 2021-01-18 16:50:02 UTC
